// Auto-run memo assembly — the REPL's `/skill <arg> --run` finishes what the
// plain `/skill <arg>` preview started ("Run the steps above, or copy them
// into a script."): actually execute each step and stitch the results into a
// single cited Markdown due-diligence memo. Pure so the format is unit-testable
// without spawning anything; app.tsx supplies the already-collected results.

import type { SkillShortcut } from "./catalog.ts"

export interface SkillStepResult {
  label: string
  command: string
  metered: boolean
  stdout: string
  stderr: string
  ok: boolean
}

/** Assemble a Markdown memo from a shortcut's auto-run step results. */
export function buildDdMemo(shortcut: SkillShortcut, arg: string, results: SkillStepResult[]): string {
  const lines: string[] = [
    `# ${shortcut.title}${arg ? `: ${arg.toUpperCase()}` : ""}`,
    "",
    shortcut.summary,
    "",
  ]
  for (const result of results) {
    lines.push(`## ${result.label}${result.metered ? " 💲" : ""}`)
    lines.push("")
    lines.push(`\`${result.command}\``)
    lines.push("")
    if (!result.ok) {
      lines.push(`_Failed: ${result.stderr.trim() || "unknown error"}_`)
    } else if (result.stdout.trim() === "") {
      lines.push("_(no output)_")
    } else {
      lines.push("```json")
      lines.push(result.stdout.trim())
      lines.push("```")
    }
    lines.push("")
  }
  const failed = results.filter((r) => !r.ok).length
  lines.push("---")
  lines.push(
    `Generated by \`/${shortcut.slash}${arg ? ` ${arg}` : ""} --run\` — ${results.length} step(s), ${failed} failed.`,
  )
  return lines.join("\n")
}
